[tool.bumpversion]
current_version = "0.3.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = [
  "{major}.{minor}.{patch}"
]
search = "v{current_version}"
replace = "v{new_version}"
tag = "True"
tag_name = "v{new_version}"
tag_message = "Bump version: v{current_version} --> v{new_version}"
commit = "True"
message = "Bump version: v{current_version} --> v{new_version}"

[[tool.bumpversion.files]]
filename = "VERSION.txt"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(?:-(?P<pre_l>[a-z]+)(?P<pre_n>0|[1-9]\\d*))?"
serialize = [
	"{major}.{minor}.{patch}-{pre_l}{distance_to_latest_tag}",
	"{major}.{minor}.{patch}"
]
search = "v{current_version}"
replace = "v{new_version}"

[[tool.bumpversion.files]]
filename = "CHANGELOG.md"
search = "#### unreleased"
replace = "#### v{new_version}"

[tool.bumpversion.parts.pre_l]
values = [
  "dev",
  "rc"
]
optional_value = "rc"
