---
- hosts: localhost
  connection: local

  vars_files:
    - "defaults/main.yml"

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "vars/config-devel.yml"
      tags:
        - always

  tasks:
    - include_role:
        name: geerlingguy.dotfiles
      when: configure_dotfiles
      tags:
        - dotfiles

    - import_tasks: tasks/main.yml
      tags:
        - homebrew

    - import_tasks: "{{ item }}"
      with_fileglob:
        - "{{ post_provision_tasks | default(omit) }}"
      tags:
        - profile
