---
- hosts: localhost
  connection: local

  vars_files:
    - "defaults/main.yml"

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "vars/config-devel.yml"
      tags:
        - always

  tasks:
    - name: Add dotfiles
      include_role:
        name: geerlingguy.dotfiles
      when: configure_dotfiles
      tags:
        - dotfiles

    - include_tasks: tasks/main.yml
      tags:
        - homebrew

    - name: Run configured post-provision tasks
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks | default(omit) }}"
      tags:
        - profile
