---
- name: Display setup profile
  debug:
      msg: "Setup for profile: Developer"

# Install Taps
- name: Install Homebrew taps
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps_devel }}"

# Install Homebrew packages
- name: Install Homebrew packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    state: present
    install_options: "{{ item.install_options | default(omit) }}"
  with_items: "{{ homebrew_installed_packages_devel }}"

- name: Uninstall blacklisted Homebrew packages
  homebrew_cask:
    name: "{{ item }}"
    state: absent
  with_items: "{{ homebrew_uninstalled_packages_devel }}"

# Install Cask applications
- name: Install Cask applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir={{ homebrew_cask_appdir }}"
  with_items: "{{ homebrew_cask_apps_devel }}"

- name: Uninstall blacklisted Cask applications
  homebrew_cask:
    name: "{{ item }}"
    state: absent
  with_items: "{{ homebrew_cask_uninstalled_apps_devel }}"

# Node.JS
- name: Install global NPM packages
  npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    global: yes
    executable: "{{ item.executable | default(omit) }}"
  with_items: "{{ npm_packages_devel }}"

# Python
- name: Install global PIP packages
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default(omit) }}"
  with_items: "{{ pip_packages_devel }}"

# Ruby
- name: Install global Ruby gems
  gem:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    user_install: no
    executable: "{{ item.executable | default(omit) }}"
  with_items: "{{ gem_packages_devel }}"
