---
# Install brew if not already installed.
- name: Check if Homebrew already installed
  stat:
    path: "/usr/local/bin/brew"
  register: homebrew_binary

- name: install Homebrew via the curl oneliner
  shell: 'ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  when: homebrew_binary.stat.exists == false
  args:
    creates: '/usr/local/bin/brew'

# Update
- name: update and upgrade homebrew
  become: False
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

# Imports
- import_tasks: common-config.yml
  tags:
    - common
    - homebrew
    - osx

- import_tasks: homebrew-updates.yml
  tags:
    - homebrew
    - updates

- import_tasks: osx.yml
  when: configure_osx
  tags:
    - homebrew
    - osx

- import_tasks: setup-cli.yml
  tags:
    - homebrew
    - osx
