---
# Setup CLI shell
- name: Add bash4 to the allowed shells
  become: yes
  lineinfile:
    dest: "/etc/shells"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    create: true
  with_items:
    - regexp: '^/usr/local/bin/bash'
      line: '/usr/local/bin/bash'

- name: Register the current shell
  shell: "echo ${SHELL}"
  register: current_shell_result
  changed_when: False

- name: Change shell for the current user
  become: yes
  shell: "chsh -s /usr/local/bin/bash {{ lookup('env','USER') }}"
  when: current_shell_result.stdout != "/usr/local/bin/bash"

# Setup bash-it, https://github.com/Bash-it/bash-it#installation
- name: Check for bash-it
  stat:
    path: "~/.bash-it"
  register: bash_it_exists

- name: Get bash-it
  git:
    accept_hostkey: yes
    clone: "yes"
    repo: "https://github.com/Bash-it/bash-it.git"
    depth: 1
    dest: "~/.bash_it"
  when: not bash_it_exists.stat.exists

- name: Install bash-it
  command: "~/.bash_it/install.sh --silent"
  when: not bash_it_exists.stat.exists

- name: Update bash-it
  command: "bash-it update"
  when: bash_it_exists.stat.exists
