---
# Setup CLI shell
- name: Add bash4 to the allowed shells
  become: yes
  lineinfile:
    dest: "/etc/shells"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    create: true
  with_items:
    - regexp: '^/usr/local/bin/bash'
      line: '/usr/local/bin/bash'

- name: Register the current shell
  shell: "echo ${SHELL}"
  register: current_shell_result
  changed_when: False

- name: Change shell for the current user
  become: yes
  shell: "chsh -s /usr/local/bin/bash {{ lookup('env','USER') }}"
  when: current_shell_result.stdout != "/usr/local/bin/bash"
