---
- name: Reload launchd
  become: yes
  shell: 'launchctl unload /Library/LaunchDaemons/homebrew.macbuild.brewupdate.plist && launchctl load /Library/LaunchDaemons/homebrew.macbuild.brewupdate.plist'

- name: Restart launchd
  become: yes
  shell: 'launchctl stop homebrew.macbuild.brewupdate.plist && launchctl start homebrew.macbuild.brewupdate.plist'
