---
configure_dotfiles: yes
configure_osx: yes

osx_script: "~/.osx --no-restart"

dotfiles_repo: "https://github.com/cgswong/dotfiles.git"
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: "~/dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - ".bash_profile"
  - ".bash_prompt"
  - ".bashrc"
  - ".curlrc"
  - ".gitconfig"
  - ".gitignore"
  - ".inputrc"
  - ".osx"
  - ".vimrc"
  - ".zshrc"
  - "a_path.bash"
  - "b_aliases.bash"
  - "c_functions.bash"
  - "e_extra.bash"

# Homebrew, see `geerlingguy.homebrew` role (https://github.com/geerlingguy/ansible-role-homebrew) documentation for usage instructions.
homebrew_brewfile_dir: "~"
homebrew_use_brewfile: true

homebrew_installed_packages:
  - asciidoc
  - asciinema
  - autoconf
  - automake
  - awscli
  - bash
  - bash-completion@2
  - bats
  - browser
  - cli53
  - corectl
  - coreutils
  - curl
  - diffutils
  - direnv
  - dnsmasq
  - dnsperf
  - dnstracer
  - docbook
  - docker-cloud
  - doxygen
  - etcd
  - fdupes
  - figlet
  - file-formula
  - findutils
  - fleetctl
  - fontconfig
  - gawk
  - gettext
  - ghostscript
  - gifsicle
  - git
  - git-extras
  - git-flow
  - git-secrets
  - giter8
  - github-release
  - gnu-sed
  - gnu-tar
  - gnu-which
  - gnupg2
  - gnutls
  - go
  - godep
  - gpatch
  - graphviz
  - grep
  - gzip
  - htop
  - httpie
  - httpstat
  - hub
  - hugo
  - iperf
  - jq
  - kops
  - kubectx
  - kubernetes-cli
  - kubernetes-helm
  - lame
  - less
  - lynx
  - make
  - mcrypt
  - mkdocs
  - neovim
  - nmap
  - node
  - nomad
  - nvm
  - openssh
  - packer
  - pandoc
  - pipenv
  - pv
  - pwgen
  - pyenv
  - pyenv-virtualenv
  - pyenv-virtualenvwrapper
  - rbenv
  - rename
  - rsync
  - s3cmd
  - skaffold
  - slackcat
  - ssh-copy-id
  - sshuttle
  - tcptrace
  - terminal-notifier
  - terraform
  - tig
  - tmux
  - tree
  - unzip
  - vault
  - vim
  - watch
  - wdiff
  - webkit2png
  - wget
  - wrk

homebrew_uninstalled_packages: []

homebrew_taps:
  - caskroom/cask
  - caskroom/fonts
  - homebrew/services

homebrew_cask_appdir: "/Applications"
homebrew_cask_apps:
  - atom
  - chefdk
  - clipmenu
  - docker
  - evernote
  - flux
  - flycut
  - github-desktop
  - google-chrome
  - handbrake
  - imageoptim
  - iterm2
  - java
  - keybase
  - launchcontrol
  - licecap
  - ngrok
  - pgadmin4
  - postman
  - qlcolorcode
  - qlmarkdown
  - qlstephen
  - quicklook-json
  - recordit
  - skitch
  - slack
  - sourcetree
  - the-unarchiver
  - transmission
  - vagrant
  - vagrant-manager
  - virtualbox
  - virtualbox-extension-pack
  - vlc
  - wireshark

homebrew_cask_uninstalled_apps: []

# Install packages from other package managers.
# Note: Ensure the required package managers are installed, eg. through homebrew.
#gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1"
gem_packages:
  - name: bundler
    state: latest
  - name: octodown
    state: latest
  - name: vagrant-dnsmasq
    state: latest
  - name: yaml-lint
    state: latest

#npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6"
npm_packages:
  - name: serverless
    state: latest
  - name: serverless-cf-vars
    state: latest
  - name: serverless-kms-secrets
    state: latest

#pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3"
pip_packages:
  - name: ansible-lint
    state: latest
  - name: boto3
    state: latest
  - name: docker-py
    state: latest
  - name: flake8
    state: latest
  - name: kube-shell
    state: latest
  - name: mkdocs
    state: latest
  - name: mkdocs-material
    state: latest
  - name: pylint
    state: latest
  - name: s4cmd
    state: latest
  - name: yamllint
    state: latest

# Glob pattern to Ansible task files to run after all other tasks are finished.
post_provision_tasks: []
